// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/review/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Feedback      string                 `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_proto_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReviewRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *ReviewRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,3,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Feedback      string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_proto_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReviewResponse) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *ReviewResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReviewResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *ReviewResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreelancerId  string                 `protobuf:"bytes,1,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewRequest) Reset() {
	*x = GetReviewRequest{}
	mi := &file_proto_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewRequest) ProtoMessage() {}

func (x *GetReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewRequest.ProtoReflect.Descriptor instead.
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{2}
}

func (x *GetReviewRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

type ReviewListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*ReviewResponse      `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_proto_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewListResponse) GetReviews() []*ReviewResponse {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_proto_review_review_proto protoreflect.FileDescriptor

const file_proto_review_review_proto_rawDesc = "" +
	"\n" +
	"\x19proto/review/review.proto\x12\x06review\"\xa4\x01\n" +
	"\rReviewRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback\"\xd4\x01\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rfreelancer_id\x18\x03 \x01(\tR\ffreelancerId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"7\n" +
	"\x10GetReviewRequest\x12#\n" +
	"\rfreelancer_id\x18\x01 \x01(\tR\ffreelancerId\"F\n" +
	"\x12ReviewListResponse\x120\n" +
	"\areviews\x18\x01 \x03(\v2\x16.review.ReviewResponseR\areviews2\x9c\x01\n" +
	"\rReviewService\x12=\n" +
	"\fSubmitReview\x12\x15.review.ReviewRequest\x1a\x16.review.ReviewResponse\x12L\n" +
	"\x14GetFreelancerReviews\x12\x18.review.GetReviewRequest\x1a\x1a.review.ReviewListResponseB=Z;github.com/Prototype-1/freelanceX_user_service/proto/reviewb\x06proto3"

var (
	file_proto_review_review_proto_rawDescOnce sync.Once
	file_proto_review_review_proto_rawDescData []byte
)

func file_proto_review_review_proto_rawDescGZIP() []byte {
	file_proto_review_review_proto_rawDescOnce.Do(func() {
		file_proto_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_review_proto_rawDesc), len(file_proto_review_review_proto_rawDesc)))
	})
	return file_proto_review_review_proto_rawDescData
}

var file_proto_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_review_review_proto_goTypes = []any{
	(*ReviewRequest)(nil),      // 0: review.ReviewRequest
	(*ReviewResponse)(nil),     // 1: review.ReviewResponse
	(*GetReviewRequest)(nil),   // 2: review.GetReviewRequest
	(*ReviewListResponse)(nil), // 3: review.ReviewListResponse
}
var file_proto_review_review_proto_depIdxs = []int32{
	1, // 0: review.ReviewListResponse.reviews:type_name -> review.ReviewResponse
	0, // 1: review.ReviewService.SubmitReview:input_type -> review.ReviewRequest
	2, // 2: review.ReviewService.GetFreelancerReviews:input_type -> review.GetReviewRequest
	1, // 3: review.ReviewService.SubmitReview:output_type -> review.ReviewResponse
	3, // 4: review.ReviewService.GetFreelancerReviews:output_type -> review.ReviewListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_review_review_proto_init() }
func file_proto_review_review_proto_init() {
	if File_proto_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_review_proto_rawDesc), len(file_proto_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_review_proto_goTypes,
		DependencyIndexes: file_proto_review_review_proto_depIdxs,
		MessageInfos:      file_proto_review_review_proto_msgTypes,
	}.Build()
	File_proto_review_review_proto = out.File
	file_proto_review_review_proto_goTypes = nil
	file_proto_review_review_proto_depIdxs = nil
}
