// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/profile/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bio               string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	HourlyRate        float32                `protobuf:"fixed32,4,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Skills            []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	Languages         []string               `protobuf:"bytes,7,rep,name=languages,proto3" json:"languages,omitempty"`
	Certifications    []string               `protobuf:"bytes,8,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Location          string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	ResponseTime      string                 `protobuf:"bytes,10,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *CreateProfileRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *CreateProfileRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateProfileRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *CreateProfileRequest) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *CreateProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateProfileRequest) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bio               string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	HourlyRate        float32                `protobuf:"fixed32,4,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Skills            []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	Languages         []string               `protobuf:"bytes,7,rep,name=languages,proto3" json:"languages,omitempty"`
	Certifications    []string               `protobuf:"bytes,8,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Location          string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	ResponseTime      string                 `protobuf:"bytes,10,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *UpdateProfileRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *UpdateProfileRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateProfileRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *UpdateProfileRequest) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *UpdateProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateProfileRequest) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bio               string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	HourlyRate        float32                `protobuf:"fixed32,4,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Skills            []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	Languages         []string               `protobuf:"bytes,7,rep,name=languages,proto3" json:"languages,omitempty"`
	Certifications    []string               `protobuf:"bytes,8,rep,name=certifications,proto3" json:"certifications,omitempty"`
	Location          string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	ResponseTime      string                 `protobuf:"bytes,10,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetProfileResponse) GetHourlyRate() float32 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *GetProfileResponse) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *GetProfileResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetProfileResponse) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *GetProfileResponse) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *GetProfileResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetProfileResponse) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

var File_proto_profile_profile_proto protoreflect.FileDescriptor

const file_proto_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/profile/profile.proto\x12\aprofile\"\xc7\x02\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1f\n" +
	"\vhourly_rate\x18\x04 \x01(\x02R\n" +
	"hourlyRate\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12\x1c\n" +
	"\tlanguages\x18\a \x03(\tR\tlanguages\x12&\n" +
	"\x0ecertifications\x18\b \x03(\tR\x0ecertifications\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12#\n" +
	"\rresponse_time\x18\n" +
	" \x01(\tR\fresponseTime\"1\n" +
	"\x15CreateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc7\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1f\n" +
	"\vhourly_rate\x18\x04 \x01(\x02R\n" +
	"hourlyRate\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12\x1c\n" +
	"\tlanguages\x18\a \x03(\tR\tlanguages\x12&\n" +
	"\x0ecertifications\x18\b \x03(\tR\x0ecertifications\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12#\n" +
	"\rresponse_time\x18\n" +
	" \x01(\tR\fresponseTime\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc5\x02\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1f\n" +
	"\vhourly_rate\x18\x04 \x01(\x02R\n" +
	"hourlyRate\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12\x1c\n" +
	"\tlanguages\x18\a \x03(\tR\tlanguages\x12&\n" +
	"\x0ecertifications\x18\b \x03(\tR\x0ecertifications\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12#\n" +
	"\rresponse_time\x18\n" +
	" \x01(\tR\fresponseTime2\xf7\x01\n" +
	"\x0eProfileService\x12N\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x1e.profile.UpdateProfileResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.GetProfileResponseB>Z<github.com/Prototype-1/freelanceX_user_service/proto/profileb\x06proto3"

var (
	file_proto_profile_profile_proto_rawDescOnce sync.Once
	file_proto_profile_profile_proto_rawDescData []byte
)

func file_proto_profile_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)))
	})
	return file_proto_profile_profile_proto_rawDescData
}

var file_proto_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_profile_profile_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),  // 0: profile.CreateProfileRequest
	(*CreateProfileResponse)(nil), // 1: profile.CreateProfileResponse
	(*UpdateProfileRequest)(nil),  // 2: profile.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 3: profile.UpdateProfileResponse
	(*GetProfileRequest)(nil),     // 4: profile.GetProfileRequest
	(*GetProfileResponse)(nil),    // 5: profile.GetProfileResponse
}
var file_proto_profile_profile_proto_depIdxs = []int32{
	0, // 0: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	2, // 1: profile.ProfileService.UpdateProfile:input_type -> profile.UpdateProfileRequest
	4, // 2: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	1, // 3: profile.ProfileService.CreateProfile:output_type -> profile.CreateProfileResponse
	3, // 4: profile.ProfileService.UpdateProfile:output_type -> profile.UpdateProfileResponse
	5, // 5: profile.ProfileService.GetProfile:output_type -> profile.GetProfileResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_profile_profile_proto_init() }
func file_proto_profile_profile_proto_init() {
	if File_proto_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_profile_proto = out.File
	file_proto_profile_profile_proto_goTypes = nil
	file_proto_profile_profile_proto_depIdxs = nil
}
