// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/portfolio/portfolio.proto

package portfolio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Portfolio message definition
type CreatePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreelancerId  string                 `protobuf:"bytes,1,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePortfolioRequest) Reset() {
	*x = CreatePortfolioRequest{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioRequest) ProtoMessage() {}

func (x *CreatePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioRequest.ProtoReflect.Descriptor instead.
func (*CreatePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePortfolioRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *CreatePortfolioRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePortfolioRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePortfolioRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreatePortfolioRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type CreatePortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePortfolioResponse) Reset() {
	*x = CreatePortfolioResponse{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioResponse) ProtoMessage() {}

func (x *CreatePortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioResponse.ProtoReflect.Descriptor instead.
func (*CreatePortfolioResponse) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePortfolioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreelancerId  string                 `protobuf:"bytes,1,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioRequest) Reset() {
	*x = GetPortfolioRequest{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioRequest) ProtoMessage() {}

func (x *GetPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *GetPortfolioRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

type GetPortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portfolio     []*PortfolioItem       `protobuf:"bytes,1,rep,name=portfolio,proto3" json:"portfolio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioResponse) Reset() {
	*x = GetPortfolioResponse{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioResponse) ProtoMessage() {}

func (x *GetPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *GetPortfolioResponse) GetPortfolio() []*PortfolioItem {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

type PortfolioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioItem) Reset() {
	*x = PortfolioItem{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioItem) ProtoMessage() {}

func (x *PortfolioItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioItem.ProtoReflect.Descriptor instead.
func (*PortfolioItem) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *PortfolioItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortfolioItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PortfolioItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PortfolioItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PortfolioItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PortfolioItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeletePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId   string                 `protobuf:"bytes,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePortfolioRequest) Reset() {
	*x = DeletePortfolioRequest{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePortfolioRequest) ProtoMessage() {}

func (x *DeletePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePortfolioRequest.ProtoReflect.Descriptor instead.
func (*DeletePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePortfolioRequest) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

type DeletePortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePortfolioResponse) Reset() {
	*x = DeletePortfolioResponse{}
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePortfolioResponse) ProtoMessage() {}

func (x *DeletePortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portfolio_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePortfolioResponse.ProtoReflect.Descriptor instead.
func (*DeletePortfolioResponse) Descriptor() ([]byte, []int) {
	return file_proto_portfolio_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePortfolioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_portfolio_portfolio_proto protoreflect.FileDescriptor

const file_proto_portfolio_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/portfolio/portfolio.proto\x12\tportfolio\"\xa6\x01\n" +
	"\x16CreatePortfolioRequest\x12#\n" +
	"\rfreelancer_id\x18\x01 \x01(\tR\ffreelancerId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\"3\n" +
	"\x17CreatePortfolioResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x13GetPortfolioRequest\x12#\n" +
	"\rfreelancer_id\x18\x01 \x01(\tR\ffreelancerId\"N\n" +
	"\x14GetPortfolioResponse\x126\n" +
	"\tportfolio\x18\x01 \x03(\v2\x18.portfolio.PortfolioItemR\tportfolio\"\xa7\x01\n" +
	"\rPortfolioItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\";\n" +
	"\x16DeletePortfolioRequest\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\tR\vportfolioId\"3\n" +
	"\x17DeletePortfolioResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x97\x02\n" +
	"\x10PortfolioService\x12X\n" +
	"\x0fCreatePortfolio\x12!.portfolio.CreatePortfolioRequest\x1a\".portfolio.CreatePortfolioResponse\x12O\n" +
	"\fGetPortfolio\x12\x1e.portfolio.GetPortfolioRequest\x1a\x1f.portfolio.GetPortfolioResponse\x12X\n" +
	"\x0fDeletePortfolio\x12!.portfolio.DeletePortfolioRequest\x1a\".portfolio.DeletePortfolioResponseB@Z>github.com/Prototype-1/freelanceX_user_service/proto/portfoliob\x06proto3"

var (
	file_proto_portfolio_portfolio_proto_rawDescOnce sync.Once
	file_proto_portfolio_portfolio_proto_rawDescData []byte
)

func file_proto_portfolio_portfolio_proto_rawDescGZIP() []byte {
	file_proto_portfolio_portfolio_proto_rawDescOnce.Do(func() {
		file_proto_portfolio_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_portfolio_portfolio_proto_rawDesc), len(file_proto_portfolio_portfolio_proto_rawDesc)))
	})
	return file_proto_portfolio_portfolio_proto_rawDescData
}

var file_proto_portfolio_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_portfolio_portfolio_proto_goTypes = []any{
	(*CreatePortfolioRequest)(nil),  // 0: portfolio.CreatePortfolioRequest
	(*CreatePortfolioResponse)(nil), // 1: portfolio.CreatePortfolioResponse
	(*GetPortfolioRequest)(nil),     // 2: portfolio.GetPortfolioRequest
	(*GetPortfolioResponse)(nil),    // 3: portfolio.GetPortfolioResponse
	(*PortfolioItem)(nil),           // 4: portfolio.PortfolioItem
	(*DeletePortfolioRequest)(nil),  // 5: portfolio.DeletePortfolioRequest
	(*DeletePortfolioResponse)(nil), // 6: portfolio.DeletePortfolioResponse
}
var file_proto_portfolio_portfolio_proto_depIdxs = []int32{
	4, // 0: portfolio.GetPortfolioResponse.portfolio:type_name -> portfolio.PortfolioItem
	0, // 1: portfolio.PortfolioService.CreatePortfolio:input_type -> portfolio.CreatePortfolioRequest
	2, // 2: portfolio.PortfolioService.GetPortfolio:input_type -> portfolio.GetPortfolioRequest
	5, // 3: portfolio.PortfolioService.DeletePortfolio:input_type -> portfolio.DeletePortfolioRequest
	1, // 4: portfolio.PortfolioService.CreatePortfolio:output_type -> portfolio.CreatePortfolioResponse
	3, // 5: portfolio.PortfolioService.GetPortfolio:output_type -> portfolio.GetPortfolioResponse
	6, // 6: portfolio.PortfolioService.DeletePortfolio:output_type -> portfolio.DeletePortfolioResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_portfolio_portfolio_proto_init() }
func file_proto_portfolio_portfolio_proto_init() {
	if File_proto_portfolio_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_portfolio_portfolio_proto_rawDesc), len(file_proto_portfolio_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_portfolio_portfolio_proto_goTypes,
		DependencyIndexes: file_proto_portfolio_portfolio_proto_depIdxs,
		MessageInfos:      file_proto_portfolio_portfolio_proto_msgTypes,
	}.Build()
	File_proto_portfolio_portfolio_proto = out.File
	file_proto_portfolio_portfolio_proto_goTypes = nil
	file_proto_portfolio_portfolio_proto_depIdxs = nil
}
