name: CD - Deploy to GKE
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: freelancex-cluster
          location: asia-south1-a
          project_id: freelancex-463106
      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f k8s/user-service/secret.yaml
          kubectl apply -f k8s/user-service/deployment.yaml
          kubectl apply -f k8s/user-service/service.yaml