name: CD - Deploy to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: freelancex-463106
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: freelancex-cluster
          location: asia-south1-a
          project_id: freelancex-463106

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f k8s/user-service/secret.yaml
          kubectl apply -f k8s/user-service/deployment.yaml
          kubectl apply -f k8s/user-service/service.yaml
